services:
  postgres:
    image: postgres:16-alpine
    container_name: portfolio_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: portfolio
      POSTGRES_PASSWORD: portfolio
      POSTGRES_DB: portfolio_cms
    ports:
      - "5432:5432"
    volumes:
      - portfolio_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: portfolio_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  portfolio_pg_data:
